### ISSUE TITLE
_.unserialize时, children的events无效

### ISSUE THREAD

**Issue by gt945** [linb/CrossUI#1]
当_.unserialize时,如果有children,而且children设置了events, 其events是无效的.原因是执行回调时是在host中找函数.
建议_.unserialize时对所有子对象统一设置host

**Comment by linb** [comment]
_.unserialize is based on eval.

You have to setHost by yourself.

**Comment by gt945** [comment]
但是setHost只对第一个元素有效果，对children还是无效。
我目前的解决方法是用一个全局变量指向host，然后在json里面将host设为该变量。
不知道有没有更优美一点的方案？

**Comment by linb** [comment]
getChildren:function(null, true)
