### ISSUE TITLE
getDirtied() bug

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#17]
if (ins.getCaption) {
                            if (key.indexOf(":") != -1) {
                                keys = key.split(':');
                              //下拉框始终为空，需要增加一个判断
                             //今天更新了最新版本，问题依旧；另外新版本Grid行双击事件也跨了，又回滚老版本了，没有深度测试
                             }
////////////////////////////////////////////////
                            if (!xui.isEmpty(keys)) {/////////////////
///////////////////////////////////////////////////
                                if (keys[0] && keys[1]) {
                                    hash[keys[0]] = uv;
                                    hash[keys[1]] = ins.getCaption();
                                }
                            } else if (withCaption) {

**Comment by linb** [comment]
更新了下版本，再试一下

2018-03-28 17:14 GMT+08:00 yr2018 <notifications@github.com>:
