### ISSUE TITLE
xui.UI.Gallery

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#19]
xui.create("xui.UI.Gallery")
                .setHost(host,"xui_ui_gallery3")
                .setItems([
                    {
                        "id":"a",
                        "caption":"item 1",
                        "image":"{/}img/article.png",
                        "imageClass":"xui-icon-number1",
                        "itemWidth":"64",
                        "itemHeight":"64",
                        "flagText":"荐"
                    },

调式了很久，发现一个问题。设置image图片地址，刷新浏览器显示不出来（貌似是第一次加载图片不显示），看资源文件，图片是加载成功的。

**Comment by linb** [comment]
I can't locate your problem
Would you make a project to show this issue on 在http://www.crossui.com/RAD ?

**Comment by yr2018** [comment]
http://www.crossui.com/RAD/XUIWorkSpace/MyPrj1/debug.html#debug=1&dir=http%3A%2F%2Fwww.crossui.com%2FRAD%2FXUIWorkSpace%2FMyPrj1%2F&height=600&touch=0&width=800

Firefox >F12>Clear Cache>

**Comment by linb** [comment]
Fixed.
