### ISSUE TITLE
 hide a dialog, can't show again

### ISSUE THREAD

**Issue by gt945** [linb/CrossUI#2]
version: 1.3

step to  reproduction:
1.create a app via xui.ComFactory.newCom, there is only one dialog in this app
2.hide it by call dialog_name.hide(); 
3.show it by call dialog_name.show(); 

result:
the dialog can't show again

debug:
when call show, profile.inShowing is set to 1,  the profile.inShowing should be deleted in callback but the callback never be called.
then, call hide and call show again, the profile.inShowing is 1 and the function return immediately

**Comment by linb** [comment]
I need your code to reproduct it.

**Comment by gt945** [comment]
I have find the root cause, this issue occurs only if customAppend return false.
