### ISSUE TITLE
add multiple

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#22]
append(
                xui.create("xui.UI.ComboInput")
                .setHost(host,"xui_ui_comboinput4")
                .setLeft("11.666666666666666em")
                .setTop("7.5em")
                .setWidth("18em")
                .setLabelSize("8em")              
                .setType("file")
            );
-----------------------------------------------------------------------
add multiple???

**Comment by linb** [comment]
I didn't get your point

**Comment by yr2018** [comment]
<input type="file" id="file" multiple="multiple"  />

**Comment by yr2018** [comment]
`<input type="file" id="file" multiple="multiple" size="200" />  `

**Comment by yr2018** [comment]
multiple="multiple"       attribute

**Comment by linb** [comment]
Dont support "multiple"  attr yet, we'll add fileAccept/fileMultiple prop in the next minor version.

Currently, you can do it in onrender event: 

xui.Class('App', 'xui.Module',{
    Instance:{
        iniComponents : function(){
            // [[Code created by CrossUI RAD Studio
            var host=this, children=[], append=function(child){children.push(child.get(0));};
            
            append(
                xui.create("xui.UI.ComboInput")
                .setHost(host,"xui_ui_comboinput7")
                .setLeft("8.333333333333334em")
                .setTop("1.6666666666666667em")
                .setWidth("18em")
                .setLabelSize("8em")
                .setLabelCaption("multiple")
                .setType("file")
                .onRender("_xui_ui_comboinput7_onrender")
            );
            
            return children;
            // ]]Code created by CrossUI RAD Studio
        },
        _xui_ui_comboinput7_onrender:function (profile){
            profile.getSubNode("FILE").attr('multiple','multiple');
        }
    }
});
