### ISSUE TITLE
 why the error "_ is not defined”  ??

### ISSUE THREAD

**Issue by iotclouddeveloper** [linb/CrossUI#23]
![1](https://user-images.githubusercontent.com/34469153/39587332-d1ded04c-4f2b-11e8-8e3b-2192e5919a26.png)

hello. when I test XUI2.0 java backend,the demo.html has the error , What is the reason?
thanks.

**Comment by linb** [comment]
The Name Space  _ doesn't exist no longer, change to xui.serialize ....

**Comment by iotclouddeveloper** [comment]
thanks
