### ISSUE TITLE
How to generate.html

### ISSUE THREAD

**Issue by wowoName** [linb/CrossUI#25]
When I installed the demo for development, I found that it would call request.php to generate.html when it was published

**Comment by linb** [comment]
Didn't get your point

**Comment by wowoName** [comment]
When I call request.php to generate the HTML file

prompt

"Class RAD2 could not be found. At (-1)"

I want to know how this file is generated

**Comment by wowoName** [comment]
或者说有什么方法可以直接获取到我编辑完成的页面保存为html文件

**Comment by wowoName** [comment]
Or is there a way to go directly to the page that I've edited and save it as an HTML file

**Comment by linb** [comment]
Which version you'd installed?  window ? oxs? linux?

**Comment by wowoName** [comment]
the browser

**Comment by linb** [comment]
We didn't offer the browser designer version. Can you tell me the download url ?

**Comment by wowoName** [comment]
we are now discussing the feasibility scheme so now from the website to see https://www.crossui.com/RAD/Builder.html

**Comment by linb** [comment]
This simple builder can't save file, you should check this one: https://www.crossui.com/RAD/index.html

**Comment by wowoName** [comment]
ok, thank you very much
