### ISSUE TITLE
xui.showModule

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#26]
Xui.showmodule spans the load module, okay？Xui.showmodule('www.abc.com/j.js')

**Comment by linb** [comment]
You can use 
xui.launch("http://www.abc.com/j.js")

**Comment by yr2018** [comment]
xui.launch(“http://zhjd.wsidom.cn/App/zhjd/main.js”, function (e, m) {
                        xui.echo("b");
                        xui.echo(m); 
                         m.show(); **//is null**
                    }); 

HELP!HELP!HELP!HELP!HELP!

**Comment by yr2018** [comment]
![Uploading QQ截图20190521112807.jpg…]()

**Comment by yr2018** [comment]
ok!

 xui.fetchClass(item.tagVar.host);
                    xui.Thread.repeat(function () {
                        if (xui.isDefined(item.tagVar.path)) {
                            xui.launch(item.tagVar.path, function () {
                                xui.echo("b");
                            });
                            return false;
                        }
                    }, 500); 

thank you!!!!

**Comment by linb** [comment]
`xui.fetchClass("http://zhjd.wsidom.cn/App/zhjd/main.js",function(url, cls){
   // Since your classpath is not the xui way (App/js/zhjd/main.js), you cant get the class object directly
   // use xui.SC to get the Class
   cls = xui.SC('App.zhjd.main');
   if(cls){
      (new cls).show();
   }
});`
