### ISSUE TITLE
Packaging error

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#28]
PC:Windows10;
out: windows 64;
**/.settings** Folder name error
CrossUI Front-Ent Builder 2.19  free version
look at the picture
![QQ截图20190606172339](https://user-images.githubusercontent.com/35554514/59022188-dbb7f100-887f-11e9-9f53-02202c0a0c3f.jpg)

**Comment by linb** [comment]
We'll fix this in next minor version, about a week
