### ISSUE TITLE
Possibility to turn the xui.confirm to SYNC function

### ISSUE THREAD

**Issue by macscripter** [linb/CrossUI#3]
Hi,
there is a nice xui.confirm function:

xui.confirm('title','content content content content content content content content content content content content ',function(){
    alert('yes')
},
function(){
    alert('no')
})

The problem is that I want to write 10 confirm for my app.

How could I reuse this function to iterate 10 confirmations? I suspect that I need to turn is as sync....

Thank you

**Comment by linb** [comment]
We have to use async mechanism in js. Unless you use the browser's built-in confirm function.
