### ISSUE TITLE
Compressed Code & typo

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#31]
CrossUI v.2.40
1. some code in code view, still used compressed code, like _page_onmessage, _page_onglobalmessage, _page_onfragmentchanged, etc
2. typo in xui_debug.js?: beforeUnitUpdated:function(prfole,unit){} and afterUnitUpdated:function(prfole,unit){} (Combo Input EventHandlers), maybe it should be "profile"

**Comment by linb** [comment]
1. That because we didn't add those functions API description, and we added those in the latest version.
2. Yes, it's "profile"
