### ISSUE TITLE
Multi file upload, will the dome appear?

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#32]
.setType("file")
 .setFileMultiple(true)
+
xui.request

Multi file upload, will the dome appear?

**Comment by linb** [comment]
I didn't get your point. Would you please give me more specific detail?

**Comment by yr2018** [comment]
Multi file upload, will the demo url?

**Comment by yr2018** [comment]
The split-by-size feature is similar to splitting by delimiter because you use it to divide a file into smaller chunks and transfer them to the endpoint component one by one.

**Comment by linb** [comment]
No demo yet
