### ISSUE TITLE
Stacks Component: show close button while hover

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#36]
Scenario: hover handle bar to show close button, and hide while mouseout
these below code don't work:

        _xui_ui_stacks15_beforehovereffect:function(profile, item, e, src, type){
            var ns = this, uictrl = profile.boxing();
            if (type=="mouseover") {
                uictrl.updateItem(item.id, {closeBtn:true});
            } else {
                uictrl.updateItem(item.id, {closeBtn:false});
            }
        }

**Comment by linb** [comment]
Don't use updateItem in beforeHover event, that will cause more dom nodes refreshed.

```
_xui_ui_stacks15_beforehovereffect:function(profile, item, e, src, type){
    var ns = this, uictrl = profile.boxing();
    // only for mouse event on ITEM node
    if(src == uictrl.getSubNodeByItemId("ITEM", item.id).xid())
        uictrl.getSubNodeByItemId("CLOSE", item.id).css('display', type=="mouseover"?"":"none");
}
```

**Comment by indianajava** [comment]
thanks a lot, very fast response, it works 👍
