### ISSUE TITLE
forgotten parameter

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#38]
At file xui-debug.js -> xui.Class("xui.UI.TreeGrid") -> Static -> _beforeSerialized,
whether the parameter "h" is forgotten?

op.grpCols = xui.clone(pp.grpCols, function(o,i,d){
    if(d===2&&i==='width'&& o && o!='auto'){
        h[i] = profile.$forceu(o,unit);
        return false;
    }else 
    return o!=undefined
});
op.rows = xui.clone(pp.rows, function(o,i,d){
    if(d===2&&i==='height'&& o && o!='auto'){
        h[i] = profile.$forceu(o,unit);
        return false;
    }else 
    return !map[((d===1?o.id:i)+'').charAt(0)]  && o!=undefined && ((i=="id"&&typeof(o)=="string")?o.charAt(0)!="-":true);
});

**Comment by linb** [comment]
Fixed
