### ISSUE TITLE
Include target class

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#39]
xui.include() can not include target class with header request and async:
1. xui.include("Module.Script",url+"Script.js",function(rsp){},onFail,FALSE,{header:{key:value}) => script included, asyn, but header not sent
2. xui.include("Module.Script",url+"Script.js",function(rsp){},onFail,TRUE,{header:{key:value}) => script included, header sent, but not asyn
3. onSuccess:function(rsp){ } => how to read script target?

**Comment by linb** [comment]
We used JSONP for asysn, Ajax for sync. So, no header for JSONP (script node).

If you want to send header for asyn case, use:

```
                xui.Ajax(url+"Script.js", xui.rand(), function(rsp){
                    try{xui.exec(rsp, "Module.Script")}
                    catch(e){xui.tryF(onFail, [e])}
                    xui.tryF(onSuccess);
                },onFail, 0, {asy:false} ).start();
```

And you can add option - {attrs:{id:'xxx'}} to set id for the script node

**Comment by indianajava** [comment]
ok, thks.
