### ISSUE TITLE
Need to use the EURO format for xui.UI.Input

### ISSUE THREAD

**Issue by macscripter** [linb/CrossUI#4]
Hi, 
I need to use the EURO format for currency: 12.000,34 €
For example, the user puts the 120000 and this value is formated as 12.000,00 €
Is it possible to do for xui.UI.Input?

Thank you!

**Comment by linb** [comment]
iniComponents : function(){
            // [[Code created by CrossUI RAD Studio
            var host=this, children=[], append=function(child){children.push(child.get(0));};
            
            append(
                new xui.UI.ComboInput()
                .setHost(host,"xui_ui_comboinput4")
                .setType("currency")
                .setGroupingSeparator(".")
                .setDecimalSeparator(",")
                .setCurrencyTpl("* €")
                .setValue(12000.34)
            );
            
            return children;
            // ]]Code created by CrossUI RAD Studio
        }
