### ISSUE TITLE
Editor runs slowly

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#42]
Use App Builder version 2.5 Beta.
I have about 9000 lines code, in code view, if i edit one row and then move cursor to another row to edit it, the editor become slow response. May be caused by new version of JSHINT?

**Comment by linb** [comment]
Yes, that is an issue for jslint version 2.0.
Maybe you can separate the file to small ones. And I'm considering to go back to jslint version 1.1.0 too.

**Comment by indianajava** [comment]
ok. thanks
