### ISSUE TITLE
Clicked blue star icon on image component, nothing happen

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#43]
![image](https://user-images.githubusercontent.com/50699924/91030734-d16f4780-e629-11ea-816c-ec5bb8efddd4.png)

**Comment by linb** [comment]
Fixed in online version

**Comment by indianajava** [comment]
still error while fetching image from image selector dialog.

**Comment by linb** [comment]
Oh, it's an error caused by TreeGrid modification.
Fixed it. Try it again please!

**Comment by indianajava** [comment]
it worked. thks
