### ISSUE TITLE
Asynchronous loading xui-all.min.js  

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#45]
jQuery.getScript(basepath + "xui/runtime/xui/js/xui-all.min.js")

![QQ截图20201019104056](https://user-images.githubusercontent.com/35554514/96395589-99365080-11f7-11eb-82f1-ee9a8e3a809c.png)

**Comment by linb** [comment]
Can you give me an online page for this?

**Comment by yr2018** [comment]
jQuery.getScript(basepath + "xui/runtime/xui/js/xui-all.min.js").done(function () {
            console.log("xui-all.min.js/加载成功");
            jQuery.getScript(basepath + "xui/runtime/xui/js/Coder.min.js").done(function () {
                console.log("Coder.min.js/加载成功");
                xui.tryF(onSuccess);
            })
        })

**Comment by linb** [comment]
I just tested in http://jsbin.com/, everything is OK.

**Comment by linb** [comment]
```
$.getScript("https://crossui.com/libs/2.0/js/xui-all.js").done(function () {
  console.log("xui-all.js loaded");

  $.getScript("https://crossui.com/libs/2.0/js/Coder.js").done(function () {
    console.log("Coder.js loaded");
  })

})
```

**Comment by yr2018** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <script src="/Scripts/jquery-3.3.1.min.js"></script>
    <script>
        $().ready(function () {
            $.getScript("https://crossui.com/libs/2.0/js/xui-all.js").done(function () {
                console.log("xui-all.js loaded");

                $.getScript("https://crossui.com/libs/2.0/js/Coder.js").done(function () {
                    console.log("Coder.js loaded");
                })

            })
        });
    </script>
</body>
</html>


TEST??????
![Uploading QQ截图20201019111712.png…]()

**Comment by yr2018** [comment]
![PPPPPPP](https://user-images.githubusercontent.com/35554514/96397917-27f99c00-11fd-11eb-86af-48705bb26ae9.png)
![QQ截图20201019111712](https://user-images.githubusercontent.com/35554514/96397921-29c35f80-11fd-11eb-9cff-1ac9f5451bf6.png)

**Comment by linb** [comment]
Caught it.
You can check out the latest code.
