### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#46]
a.js=   xui.Class('App.hr.info.onlogin___a', 'xui.Module'...........................
b.js=   xui.Class('App.hr.info.onlogin___b', 'xui.Module'...........................
c.js=   xui.Class('App.hr.info.onlogin___c', 'xui.Module'...........................
------------------------------------------------------------------------------
a.js+b.js+c.js=d.min.js

如何通过xui.newModule(cls........)加载这3个class       ????????????????

**Comment by linb** [comment]
Can't got point
