### ISSUE TITLE
TreeGrid.setEditMode('inline')

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#47]
1. TreeGrid.setEditable(true).setEditMode('inline') not work
2. API Documentation, click any row in search result dialog, nothing happen
3. xui.debug.js line 5574 at class xui.MessageService should be "setRecipientType"

**Comment by linb** [comment]
1.TreeGrid.setEditable(true).setEditMode('inline') not work
**You have to do this case before the TreeGrid was rendered, if the TreeGrid has rendered already, only those new cells can be editable as you want**

2.API Documentation, click any row in search result dialog, nothing happen
**Fixed**

3.xui.debug.js line 5574 at class xui.MessageService should be "setRecipientType"
**Fixed**
