### ISSUE TITLE
Ajax problem

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#49]
1. xui.Ajax with options.method = 'POST' always send as GET
2. xui.request can not upload file, because automatically use xui.Ajax instead of xui.XDMI

**Comment by linb** [comment]
Did you try:
`xui.request(uri, query, onSuccess, onFail, null, {proxyType:"ajax", method:"post", data:{...} })`
or 
`xui.request(uri, query, onSuccess, onFail, null, {proxyType:"fetch", method:"post", data:{...} })`

**Comment by indianajava** [comment]
in previous version (2.40), this code working properly to upload file:
xui.request(uri, query, onSuccess, onFail, null, {method:"post"})

also happen at https://www.crossui.com/RAD/index.html,
with image component, try to upload picture from image selector, it doesn't work

**Comment by linb** [comment]
In 3.0+, you have to add the file in data object.
`xui.request(uri, query, onSuccess, onFail, null, {proxyType:"ajax", method:"post", data:{
    "file":xxx
} })`
or
`xui.request(uri, query, onSuccess, onFail, null, {proxyType:"fetch", method:"post", data:{
    "file":xxx
} })`

**Comment by indianajava** [comment]
fetch is new feature in 3.0, what different between fetch and ajax ?

**Comment by indianajava** [comment]
oh thks
