### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#50]
In 3.0, this command triggers an error "Maximum call stack size exceeded"

xui.unserialize('new xui.UI.Button()')

**Comment by linb** [comment]
Fixed, please check it out.

**Comment by indianajava** [comment]
just downloaded, the error still occurs

**Comment by linb** [comment]
I only submitted to Github.

**Comment by indianajava** [comment]
couldn't find any changes on github regarding the bug
