### ISSUE TITLE
Send data as JSON

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#51]
APICaller version 3.0

1. send data to server:
proxyType: Fetch / Ajax
queryMethod: POST
requestType: FORM
queryData: { abc: {def:123} }

however, on the server side, the accepted parameter is: 
abc = "[object Object]"

2. how to send queryArgs { abc: {def:123} } as JSON with queryMethod GET?

**Comment by linb** [comment]
1.   requestType: FORM  is for query arguments, you can set queryData
to xui.stringify({ abc: {def:123} }), or JSON.stringify( { abc: {def:123} }
)

2. send query arguments as JSON:  json:  xui.stringify( { abc: {def:123} }
)
