### ISSUE TITLE
dateEditorTpl bug

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#52]
fill dateEditorTpl in the treeGrid header date type, if run will display the template format instead of cell value

**Comment by linb** [comment]
I didn't get you point. please give me code & snapshot for this

**Comment by indianajava** [comment]
![image](https://user-images.githubusercontent.com/50699924/112699351-3770c580-8ebe-11eb-94ef-81c485ae537d.png)

dateEditorTpl = "dd-mm-yyyy"
onfocus will display cell value
onblur display the format template

**Comment by linb** [comment]
Fixed. Please check it out in Github.
