### ISSUE TITLE
What kind of environment configuration

### ISSUE THREAD

**Issue by ptheusa** [linb/CrossUI#56]
I tested Crossu 2 a few years ago (the environment is apach2.4, php5.6, MySQL5.6 & chrome)

The current environment is apach2.4, php7.4, MySQL5.7 & chrome

Anything related to front-end and back-end data, taken from Database or JSON XML
(Crossui desktop RAD Create New Project example LoadData CRUD OrdManagement)
Regardless of whether it is Crossui 3 or desktop RAD runtime, the operation example is not normal. (Or no data is displayed or an error message appears)
![image](https://user-images.githubusercontent.com/3025992/146475827-477c03e4-c8d3-4cff-ad7f-f7ce2d16900d.png)
![image](https://user-images.githubusercontent.com/3025992/146475790-2045174a-a8a0-45e9-8d29-64055eaa5eab.png)

OrdManagement sample downloaded from the website crossui.com
![image](https://user-images.githubusercontent.com/3025992/146475680-199b155d-1ad2-43bd-a614-22561990b609.png)
![image](https://user-images.githubusercontent.com/3025992/146475726-65043825-bd7f-44f4-8277-f682a3effe09.png)

What kind of environment configuration and other suggestions should I use?

Thank you for your attention

Tom. Huang

**Comment by linb** [comment]
Caused by code update.
Fixed, pls download again.
Any problem, contact us as free.
