### ISSUE TITLE
About OrderManagement(12/18/21)

### ISSUE THREAD

**Issue by ptheusa** [linb/CrossUI#57]
The examples in the new version of Desktop2.5 have been improved
There are two minor issues:

1.	[New] a order 
If you do not enter the data, cannot exit the (Confirm) screen.
![image](https://user-images.githubusercontent.com/3025992/146641802-6743c430-f4e6-4b5d-a83a-bfbb4db436ce.png)

2.	Switch to the runtime from github, Pagegrid still has no display.
![image](https://user-images.githubusercontent.com/3025992/146641825-3a6a4e40-4335-4fd1-8875-1e6a2a4f0d4e.png)

Regards,
Tom Huang

**Comment by linb** [comment]
for question 1:  Create a new OrderManagement project, or 

1)select the dialog in Order.js
2)click 'beforeClose'  to open event editor 
3)select 2nd action - "confirm"
4)uncheck "Abort subsequent execution", and save it.

![image](https://user-images.githubusercontent.com/4043582/146684948-0426f20d-4f5f-4748-809d-2cdf9ac0205c.png)

for question 2:

Try again please
