### ISSUE TITLE
?_rnd_=38rx56ax   How to cancel

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#58]
xui.include( 'xui.Thread', '../js/clsname.js', function(){ 
    alert( 'success' ); 
}});

rul>../js/clsname.js?_rnd_=38rx56ax   
rul>../js/clsname.js    (I need)  How to do?

**Comment by linb** [comment]
`xui.include(id/*Unique name of object in your script*/,path,onSuccess,onFail,sync,options)`

1. Do not use 'xui.Thread' as id, xui.Thread is inline object name, if the id here exists, your script will not be imported.
2. If you don't like the non-caching mechanism (the extra url parameter - "?rnd=xxx"), you can set {force:false} in options, like:
 
```
xui.include( 'objectname', '../js/clsname.js', function(){
   alert( 'success' );
}, function(){
   alert( 'failed' );
}, false, {
   force: false
});

```

**Comment by linb** [comment]
And set xui.debugMode to false
`
xui.debugMode = false;`

**Comment by yr2018** [comment]
thanks very much
