### ISSUE TITLE
xui.fetchClass    feel uncertain  !!!!!

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#59]
xui.Class('App.desktop.main', 'xui.Module', {
    Instance: {
        events: {"onRender": "_render"},
        iniComponents: function () {
            const host = this, children = [], append = function (child) {
                children.push(child.get(0));
            };
            append(
                xui.create("xui.UI.Gallery")
                    **_.setHost(host, "_gl_main")_** 
                    .setDock("fill")
                    .onItemSelected("__gl_main_onitemselected")
                    .beforeHoverEffect("__gl_main_beforehovereffect")
                    .beforeClickEffect("__gl_main_beforeclickeffect")
            );

            return children;
        },
-------------------------------------------------------------------------------------------
xui.fetchClass('App.desktop.main', function (cls, url) {
                cls = xui.SC.get('App.desktop.main');//类名
                if (cls) {
                    const m = cls;
                   
                    console.log(m._gl_main);    **//is undefined  ？？？？？？？？？？？？？？**

                    m.show(function (module) {
                        console.log(module._gl_main);  **//is  undefined  ？？？？？？？？？？？？？**
                    });
                }
            }, null, null, true);

**Comment by yr2018** [comment]
<script src="/app/js/ThirdParty/CrossUI/runtime/xui/js/xui.js"></script> 
<script src="/app/js/ThirdParty/CrossUI/xui/js/UI.js"></script>

**Comment by yr2018** [comment]
Minimum run Module,How to load?

**Comment by yr2018** [comment]
Has been solved

**Comment by linb** [comment]
Can not get your point. Be specific pls.
