### ISSUE TITLE
TreeGrid() question. Any chance to "freeze" the first 3 columns?

### ISSUE THREAD

**Issue by macscripter** [linb/CrossUI#6]
I have a TreeGrid related question. To keep always visible the description (for example) of each row, in excel we have the possibility to freeze the columns. Are the possibilities to implement something similar on XUI? I notice that when the rowHandler and rowNumbered are activated, we have the freeze of the first (rowHandler) column. So maybe is it any chance to freeze another columns?

Thank you

**Comment by linb** [comment]
Try freezedColumn and freezedRow please

**Comment by macscripter** [comment]
Thanks! It works perfectly!
