### ISSUE TITLE
important

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#61]
.setCustomStyle({
                        "INPUT": {
                            **"important": true,**     //of no avail
                            "color": "#FFFFFF"                          
                        }
                    });
--------------------------------------------------------------------------------------------------------
.setCustomStyle({
                        "INPUT": {                          
                            "color": "#FFFFFF **!important**"    //of no avail        
                        }
                    });
------------------------------------------------------------------------------------------------------------

How to do is css **important**  ???

**Comment by linb** [comment]
The !important tag can't be concatenated onto the end of the string. Try to use style.setProperty in  onRender event.

```
xui.Class('App', 'xui.Module',{
    Instance:{
        iniComponents : function(){
            // [[Code created by CrossUI RAD Studio
            var host=this, children=[], append=function(child){children.push(child.get(0));};
            
            append(
                xui.create("xui.UI.Label")
                .setHost(host,"xui_ui_label1")
                .setLeft("20.571428571428573em")
                .setTop("6.095238095238095em")
                .setCaption("LABEL")
                .onRender("_xui_ui_label1_onrender")
            );
            
            return children;
            // ]]Code created by CrossUI RAD Studio
        },
        _xui_ui_label1_onrender:function(profile){
            var node = profile.getSubNode("CAPTION").get(0);
            node.style.setProperty("color", "#cdcdcd", "important"); 
        }
    }
});
```

**Comment by yr2018** [comment]
thanks very much.
Be suddenly enlightened.
