### ISSUE TITLE
xui.fetchClass

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#62]
xui.Class('App.desktop.main', 'xui.Module', {
    Instance: {
        events: {"onRender": "_render"},
        iniComponents: function () {
            const host = this, children = [], append = function (child) {
                children.push(child.get(0));
            };
            append(
                **xui.create("xui.UI.Gallery")
                    .setHost(host, "_gl_main")**
                    .setDock("fill")
                    .onItemSelected("__gl_main_onitemselected")
                    .beforeHoverEffect("__gl_main_beforehovereffect")
                    .beforeClickEffect("__gl_main_beforeclickeffect")
            );

            return children;
        },
----------------------------------------------------------------------------------------------------
 xui.fetchClass("App.desktop.main", function (url, cls) {
            cls = xui.SC('App.desktop.main');
            if (cls) {
  
                   //this moment How to get Module is  **_gl_main(xui.UI.Gallery)**
                   // cls._gl_main    **is wrong**
                  // var a =new cls(); a._gl_main     **is wrong** 

                (new cls).show();   //  is ok
            }
        });

**Comment by linb** [comment]
1.  the "_gl_main" is created in the iniComponents function, meaning you must first render the instance to trigger the iniComponents function. When you create the class 'App.desktop.main' via 'new cls()', it just created a new instance, the 'iniComponents' wasn't called.
2. fetchClass will return cls object, you don't need xui.SC to get it again.
