### ISSUE TITLE
xui-debugu.js

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#63]
xui-debugu.js   7886    is bug  

    getSrc:function(event){
            var a;
            return ((a=event.target||event.srcElement||null) && xui.browser.kde && a.nodeType == 3)?a.parentNode:a
        },

**event is undefined**

**Comment by yr2018** [comment]
https://cdn.jsdelivr.net/gh/linb/CrossUI@master/runtime/xui/js/xui-debug.js

**Comment by linb** [comment]
Leave here code to reproduce it pls.

**Comment by yr2018** [comment]
append(
                xui.create("xui.UI.TreeGrid")
                .setHost(host,"xui_ui_treegrid2")
                .setLeft("0px")
                .setTop("0px")
                .setRowNumbered(true)
                .setSelMode("multibycheckbox")
                .setEditable(true)     //！！！！！！！！！！！！！！！！！！！！！！！！！！
                .setHeader([
                    {
                        "id" : "col1",
                        "width" : "105px",
                        "type" : "checkbox",   //！！！！！！！！！！！！！！！！！！！！！！！！！！！！
                        "caption" : "col1"
                    },
                    {
                        "id" : "col2",
                        "width" : "105px",
                        "type" : "input",
                        "caption" : "col2"
                    },
                    {
                        "id" : "col3",
                        "width" : "105px",
                        "type" : "input",
                        "caption" : "col3"
                    },
                    {
                        "id" : "col4",
                        "width" : "105px",
                        "type" : "input",
                        "caption" : "col4"
                    }
                ])
                .setRows([
                    {
                        "cells" : [
                            {
                                "value" : true
                            },
                            {
                                "value" : "B1"
                            },
                            {
                                "value" : "C1"
                            },
                            {
                                "value" : "D1"
                            }
                        ]
                    },
                    {
                        "cells" : [
                            {
                                "value" : true
                            },
                            {
                                "value" : "B2"
                            },
                            {
                                "value" : "C2"
                            },
                            {
                                "value" : "D2"
                            }
                        ]
                    },
                    {
                        "cells" : [
                            {
                                "value" : true
                            },
                            {
                                "value" : "B3"
                            },
                            {
                                "value" : "C3"
                            },
                            {
                                "value" : "D3"
                            }
                        ],
                        "sub" : [
                            {
                                "cells" : [
                                    "A4",
                                    "B4",
                                    "C4",
                                    "D4"
                                ]
                            }
                        ]
                    },
                    {
                        "iniFold" : false,
                        "cells" : [
                            {
                                "value" : true
                            },
                            {
                                "value" : "B5"
                            },
                            {
                                "value" : "C5"
                            },
                            {
                                "value" : "D5"
                            }
                        ],
                        "sub" : [
                            {
                                "cells" : [
                                    {
                                        "value" : true
                                    },
                                    {
                                        "value" : "B6"
                                    },
                                    {
                                        "value" : "C6"
                                    },
                                    {
                                        "value" : "D6"
                                    }
                                ]
                            }
                        ]
                    }
                ]) 
            );



//preview 》》》click  ：   "type" : "checkbox",

**Comment by linb** [comment]
Fixed, pls check it out.
