### ISSUE TITLE
xui.Dom.selectFile   

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#64]
Cross-domain can be used, the same domain can not get the file objects?
![微信图片_20230413120604](https://user-images.githubusercontent.com/35554514/231650225-4823e792-0e83-49b6-9452-d5b8923a7d41.png)

**Comment by yr2018** [comment]
xui.request  is  bug
1、www.abc.com  main is page
2、www.abc.com => js.abc.com    **load  xui-all.js**
3、www.abc.com run  xui.request () => not  xui.IAjax(xui.Dom.selectFile is ok )

**Comment by yr2018** [comment]
![微信图片_20230414134120](https://user-images.githubusercontent.com/35554514/231951523-e1b6cba7-de0d-47e0-8ff6-03ca2a2ae11a.png)

**Comment by yr2018** [comment]
xui.js  xui._getrpc()=>1513=>1523 return xui.Ajax  is wrong!    IAjax is ok

**Comment by linb** [comment]
Suggest using xui.ajax / xui.jsonp / xui.xdmi / xui.fetch directly for complicated cases.
