### ISSUE TITLE
Two questions !!!

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#66]
1. xui.message  Next version, can you add an Id attribute? I like it so much that I change the background color with it!
2. xui("id") is ok, How to achieve xui.css(".class") ???

**Comment by linb** [comment]
1. there are 3 attributes you can use to get the message: last, allmsg and stack. You can use those to get the alive messages UI 
`xui.message("xxx");
xui.asyRun(function(){
  xui.message.last.css("background", "red");
});`

2. You can try to use xui.Dom.querySelector or xui.Dom.querySelectorAll.

**Comment by yr2018** [comment]
xui.Dom.querySelectorAll(selectors)  
What type of this parameter is it? Can you give a example?

**Comment by linb** [comment]
Same as DOM's standard methods: querySelector and querySelectorAll, you can find how to use those info anywhere.

xui("dom_id").querySelector ~= document.getElementById("dom_id).querySelector

xui("dom_id").querySelectorAll ~= document.getElementById("dom_id).querySelectorAll
