### ISSUE TITLE
restore your forum in the future? 

### ISSUE THREAD

**Issue by cgetty** [linb/CrossUI#67]
Hi Jack

Do you have any plans to restore your forum in the future? 
https://www.crossui.com/Forum/index.php

Thanks 
Clark

**Comment by cgetty** [comment]
Thank you for your response. If I want to ask general questions where should I post them?

Also while I'm here I would like a tip on how to to resolve an issue I have. It not a problem with your software. Rather its a lack of programing skills on my part. Could you take a look?  http://mobile1.onlinewebshop.net/sod/vb1/

Thanks
Clark

**Comment by linb** [comment]
Hi Clark,

Please describe your problem.

All the best

**Comment by cgetty** [comment]
This program demonstrates how to read a Jason formatted file and
populate the fields on the screen. How can this file overwrite the
file tst.db (a Jason file) the one that was read from the web?  This
file  http://mobile1.onlinewebshop.net/sod/tst.db

Also to be able to save to a local disk.

The source code can be found here. https://www.crossui.com/RAD/
then open this project   elmo.ross.vb1

I hope the makes sense.
