### ISSUE TITLE
在xui.UI.RichEditor中添加<img> 会加载2次，如何只让加载一次

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#68]
https://www.crossui.com/xui/CodeSnip/index.html#/xui.UI.RichEditor
`<img src="https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png">`

![1](https://github.com/linb/CrossUI/assets/35554514/b45ed3e2-5522-42d9-b0e3-35ff32db4bbf)
![2](https://github.com/linb/CrossUI/assets/35554514/18de180e-124d-4701-9779-0ca223abccaa)

**Comment by yr2018** [comment]
我记得，有个可以自定义功能按钮的demo，找不到了，能提供一下吗？

**Comment by linb** [comment]
This one? https://www.crossui.com/ThemeRoller

**Comment by yr2018** [comment]
![4444](https://github.com/linb/CrossUI/assets/35554514/2f70f050-58e9-4aed-b518-8924343bb58a)
这个功能按钮，我需要拦截后重写，也需要增加按钮功能

**Comment by yr2018** [comment]
我目前的解决方案是：拦截后，直接写入，解决图片加载2次的情况。 
xui.Dom.byId("xui.UI.RichEditor-EDITOR:a:").contentWindow.document.getElementsByTagName("body")[0].innerHTML = html;

**Comment by yr2018** [comment]
这个UI，在销毁的时候，会再次里面的内容，如果内容有图片，每个图片会再次请求2次。目测每次重复请求，是iframe改动了，激活了浏览器主动请求。

**Comment by yr2018** [comment]
Thanks, I'll research it

**Comment by yr2018** [comment]
**Commented code can be fixed**
/CrossUI/xui/js/UI/RichEditor.js       // 1053   

`_ensureValue: function (profile, value) {
            var p = xui.$getGhostDiv();
            // p.innerHTML = (xui.isSet(value) ? value : '') + "";
            // value = p.innerHTML;
            // p.innerHTML = "";
            // return value;
            return value;
        },`

**Comment by linb** [comment]
I added a demo for integrating TinyMCE HTML Editor:

https://crossui.com/community/viewtopic.php?t=19
