### ISSUE TITLE
setActiveAnim

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#69]
xui.create("xui.UI.ToolBar")
                .setHost(host,"ui_tv_tlb")
                .setItems([
                    {
                        "id" : "grp1",
                        "sub" : [
                            {
                                "id" : "add",
                                "caption" : " ",
                                "type" : "button",
                                "imageClass" : "xui-uicmd-add",
                                "tips" : "add"
                            },
                        ],
                        "caption" : "grp1"
                    }
                ])
                .setActiveAnim("blinkAlert")
                .setTop("5.333333333333333em")
                .setHandler(false)
//////////////////////////////////////////////////////////////////////////////////

I want to add the .setActiveAnim("blinkAlert") attribute to the items in Items to remind the user, for example:
  {
                                "id" : "add",
                                "caption" : " ",
                                "type" : "button",
                                "imageClass" : "xui-uicmd-add",
                                "tips" : "add",
                                .setActiveAnim("blinkAlert")
}

**Comment by linb** [comment]
To apply animation to a node, you have to uses xui.Dom method.

`// The default code is a module class (inherited from xui.Module)
// Ensure that all the value of "key/value pair" does not refer to external variables
xui.Class('App', 'xui.Module',{
    Instance:{
        // Dependency classes
        Dependencies:[],
        // Required modules
        Required:[],

        // To initialize properties
        properties : {},

        // To initialize instance(e.g. properties)
        initialize : function(){
        },

        // To initialize internal components (mostly UI controls)
        // *** If you're not a skilled, dont modify this function manually ***
        iniComponents : function(){
            // [[Code created by CrossUI RAD Studio
            var host=this, children=[], append=function(child){children.push(child.get(0));};

            append(
                xui.create("xui.UI.ToolBar")
                .setHost(host,"ui_tv_tlb")
                .setItems([
                    {
                        "id" : "grp1",
                        "sub" : [
                            {
                                "id" : "add",
                                "caption" : " ",
                                "type" : "button",
                                "imageClass" : "xui-uicmd-add",
                                "renderer" : function(item){
                                    var ctrl = this;
                                    xui.asyRun(function(){
                                        var n = ctrl.getSubNodeByItemId("ITEM", item.id);
                                        debugger;
                                        n.animate({
                                            opacity : [1,0]
                                        }, null, null, 1000, 0, 'sineIn' ).links(
                                            n.animate({
                                            opacity : [0,1] 
                                        }, null, null, 1000, 0, 'sineOut' )).start( );
                                    });
                                },
                                "tips" : "add"
                            },
                        ],
                        "caption" : "grp1"
                    }
                ])
                .setTop("5.333333333333333em")
                .setHandler(false)
            );

            return children;
            // ]]Code created by CrossUI RAD Studio
        },

        // Give a chance to determine which UI controls will be appended to parent container
        customAppend : function(parent, subId, left, top){
            // "return false" will cause all the internal UI controls will be added to the parent panel
            return false;
        }
        /*,
        // To determine how properties affects this module
        propSetAction : function(prop){
        },
        // To set all node's style in this modlue
        customStyle:{}
    },
    //To customize the default properties and event handlers
    Static:{
        $DataModel:{
        },
        $EventHandlers:{
        }
    */
    }
});`

**Comment by linb** [comment]
Try this:

https://www.crossui.com/RAD/XUIWorkSpace/Animator-in-Toolbar/debug.html

**Comment by yr2018** [comment]
为啥不用

xui.UI.prototype.animate = function (key, callback) {}

方法？

这样在界面满足条件时，可以重复提醒用户，去操作一些动作

**Comment by yr2018** [comment]
Thank you for your reply! I still feel that the .setActiveAnim("blinkAlert") attribute is not as easy to use. If this attribute can be used in sub-items, the interface will be perfect!
