### ISSUE TITLE
Set the scrollbar at the end of the grid

### ISSUE THREAD

**Issue by macscripter** [linb/CrossUI#7]
Hello,

Does the grid have the possibility to set the scrollbar, for example, at the end of the grid? This would be useful.

Thank you!

`// The default code is a module class (inherited from xui.Module)
// Ensure that all the value of "key/value pair" does not refer to external variables
Class('App', 'xui.Module',{
    Instance:{
        // Dependency classes
        Dependencies:[],
        // Required modules
        Required:[],

        // To initialize properties
        properties : {},

        // To initialize instance(e.g. properties)
        initialize : function(){
        },

        // To initialize internal components (mostly UI controls)
        // *** If you're not a skilled, dont modify this function manually ***
        iniComponents : function(){
            // [[Code created by CrossUI RAD Studio
            var host=this, children=[], append=function(child){children.push(child.get(0));};
            
            append(
                xui.create("xui.UI.Pane")
                .setHost(host,"xui_ui_pane6")
                .setLeft(190)
                .setTop(120)
                .setWidth(370)
                .setHeight(220)
            );
            
            host.xui_ui_pane6.append(
                xui.create("xui.UI.TreeGrid")
                .setHost(host,"xui_ui_treegrid2")
                .setLeft(0)
                .setTop(0)
                .setRowNumbered(true)
                .setHeader([{
                    "id" : "col1",
                    "width" : 80,
                    "type" : "input",
                    "caption" : "col1"
                },
                {
                    "id" : "col2",
                    "width" : 80,
                    "type" : "input",
                    "caption" : "col2"
                },
                {
                    "id" : "col3",
                    "width" : 80,
                    "type" : "input",
                    "caption" : "col3"
                },
                {
                    "id" : "col4",
                    "width" : 80,
                    "type" : "input",
                    "caption" : "col4"
                }])
                .setRows([{
                    "cells" : [{
                        "value" : "row1 col1"
                    },
                    {
                        "value" : "row1 col2"
                    },
                    {
                        "value" : "row1 col3"
                    },
                    {
                        "value" : "row1 col4"
                    }]
                },
                {
                    "cells" : [{
                        "value" : "row2 col1"
                    },
                    {
                        "value" : "row2 col2"
                    },
                    {
                        "value" : "row2 col3"
                    },
                    {
                        "value" : "row2 col4"
                    }]
                },
                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                },                {
                    "cells" : [{
                        "value" : "row3 col1"
                    },
                    {
                        "value" : "row3 col2"
                    },
                    {
                        "value" : "row3 col3"
                    },
                    {
                        "value" : "row3 col4"
                    }],
                    "sub" : [{
                        "cells" : ["sub1","sub2","sub3","sub4"]
                    }]
                }])
                );
            
            return children;
            // ]]Code created by CrossUI RAD Studio
        },

        // Give a chance to determine which UI controls will be appended to parent container
        customAppend : function(parent, subId, left, top){
            // "return false" will cause all the internal UI controls will be added to the parent panel
            return false;
        }
        /*,
        // To determine how properties affects this module
        propSetAction : function(prop){
        },
        // To set all node's style in this modlue
        customStyle:{}
    },
    //To customize the default properties and event handlers
    Static:{
        $DataModel:{
        },
        $EventHandlers:{
        }
    */
    }
});`

**Comment by macscripter** [comment]
Just to add the we have the method setActiveRow(), so would be interesting to adjust the scrollbar position to the active Row!

Thanks

**Comment by linb** [comment]
tg.setActiveRow(12);
tg.getSubNodeInGrid('ROW2',12).scrollIntoView();
