### ISSUE TITLE
  .setProperties("contenteditable","true")

### ISSUE THREAD

**Issue by yr2018** [linb/CrossUI#70]
append(
                xui.create("xui.UI.Div")
                .setHost(host,"xui_ui_div51")
                .setDock("top")
                .setLeft("5.333333333333333em")
                .setTop("19.80952380952381em")
                .setWidth("24.457142857142856em")
                .setHeight("17.6em")
                .setProperties("contenteditable","true")
                .setCustomStyle({
                    "KEY" : {
                        "background-color" : "#20B2AA"
                    }
                })
            );

The contenteditable="true" attribute makes the <div> element editable. How can I add this attribute? Please guide me!

**Comment by linb** [comment]
`xui.Class('App', 'xui.Module',{
    Instance:{
        iniComponents : function(){
            // [[Code created by CrossUI RAD Studio
            var host=this, children=[], append=function(child){children.push(child.get(0));};
            
            append(
                xui.create("xui.UI.Div")
                .setHost(host,"xui_ui_div13")
                .setLeft("12.19047619047619em")
                .setTop("8.380952380952381em")
                .setPanelBgClr("#F0F8FF")
                .onRender("_xui_ui_div13_onrender")
            );
            
            return children;
            // ]]Code created by CrossUI RAD Studio
        },
        _xui_ui_div13_onrender:function(profile){
            profile.getRoot().attr("contenteditable", "true");
        }
    }
});`
