### ISSUE TITLE
What is the main difference between xui 1.4 and 2.0?

### ISSUE THREAD

**Issue by macscripter** [linb/CrossUI#9]
Hi,, 

I would like to know what is the difference between version 1.4 and 2.0? Is it possible to reuse the 1.4 version code for 2.0? Do you want to still maintaining th2 1.4 version?  could you suggest to migrate from 1.4 version?

Thank you!

**Comment by linb** [comment]
![n 78hp0 _sqh82pgdxt1](https://cloud.githubusercontent.com/assets/4043582/21413086/da3edd7e-c82f-11e6-9ba6-1cc04aab9cbb.png)

Version 2.0 is NOT compatible with older versions

1)Remove '_' namespace (merged '_' to 'xui');
2)Move 'NameSpace' to xui.NameSpace;
3)Removed some  widgets: Range/Poll/TagEditor/ColLayout/Calendar/TimeLine;
4)Removed themes 'aqua','blackwhite'; added themes 'classic' and 'webflat'.

If you want to upgrade your 1.4 code to 2.0, notice the above changed.

We will continue to maintain version1.4 .

**Comment by macscripter** [comment]
Ok, Jack, thank you!

But do you suggest to migrate to 2.0 version?
May I try to use the 2.0 RAD builder?
Thank you!

2016-12-22 2:17 GMT+00:00 Jack Lee <notifications@github.com>:
